#!/usr/bin/env python

from code import *

import hpy

class HConsole(InteractiveConsole):
    def runsource(self, src, *args, **kw):
        try:
            hsrc = hpy.translateString(src.decode('utf8'))
        except Exception:
            self.showtraceback()
        InteractiveConsole.runsource(self, hsrc, *args, **kw)

def main():
    HConsole().interact()

if __name__ == '__main__':
    main()
