#!/usr/bin/env python

from code import *

import hpy

class HConsole(InteractiveConsole):
    def runsource(self, src, *args, **kw):
        InteractiveConsole.runsource(self, hpy.translateString(src), *args, **kw)

def interact():
    HConsole().interact()

if __name__ == '__main__':
    interact()
