#!/usr/bin/env python
#-*- coding: utf-8 -*-
"""Execute and analize Hebrew Python scripts """

import hpy
from optparse import OptionParser

# Parse options
parser = OptionParser(usage='usage: %prog [options] FILE',
                      version='%prog ' + hpy.__version__)

parser.add_option("-s", "--source",
                  action="store_true", dest="source",
                  help="show translated source")

parser.add_option("-t", "--tokens",
                  action="store_true", dest="tokens",
                  help="show tokens in source")

parser.set_defaults(source=False, tokens=False)

options, args = parser.parse_args()

# Validate args
if len(args) != 1:
    parser.error('no file specified')

path = args[0]

# Run
if options.tokens:
    hpy.printTokens(path)    
if options.source:
    print hpy.source(path)

hpy.execute(path)
